package stagui

type NodeCode byte

const (
	// IDENTIFIERS
	N_COLOR NodeCode = iota
	N_PAGE
	N_BUTTON
	N_PLAINTEXT
	N_TEXTDATA
	N_IDENTIFIER

	// COMMANDS
	N_COM_RED
	N_COM_GREEN
	N_COM_BLUE
	N_COM_BGDRAW
	N_COM_BGCOLOR
	N_COM_X
	N_COM_Y
	N_COM_W
	N_COM_H
	N_COM_TEXT
	N_COM_TEXTCOLOR
	N_COM_FONT
	N_COM_FONTSIZE
	N_COM_TEXTGAP
	N_COM_HORALIGN
	N_COM_VERALIGN

	// STATEMENTS
	N_STAT_RED
	N_STAT_GREEN
	N_STAT_BLUE
	N_STAT_BGDRAW
	N_STAT_BGCOLOR
	N_STAT_X
	N_STAT_Y
	N_STAT_W
	N_STAT_H
	N_STAT_TEXT
	N_STAT_TEXTCOLOR
	N_STAT_FONT
	N_STAT_FONTSIZE
	N_STAT_TEXTGAP
	N_STAT_HORALIGN
	N_STAT_VERALIGN

	// LITERALS
	N_STRING
	N_INT
	N_ALIGN

	// BRACES
	N_L_SQUIRLY
	N_R_SQUIRLY

	// CONSTRUCTS
	N_COLOR_DEF
	N_PAGE_DEF
	N_BUTTON_DEF
	N_PLAINTEXT_DEF
	N_TEXTDATA_DEF
	N_COLOR_BLOCK
	N_PAGE_BLOCK
	N_BUTTON_BLOCK
	N_PLAINTEXT_BLOCK
	N_TEXTDATA_BLOCK
	N_PROGRAM

	N_ILLEGAL NodeCode = 255
)

var nodeCodeNames map[NodeCode]string = map[NodeCode]string{
	N_COLOR:"N_COLOR",
	N_PAGE:"N_PAGE",
	N_BUTTON:"N_BUTTON",
	N_PLAINTEXT:"N_PLAINTEXT",
	N_TEXTDATA:"N_TEXTDATA",
	N_IDENTIFIER:"N_IDENTIFIER",
	N_COM_RED:"N_COM_RED",
	N_COM_GREEN:"N_COM_GREEN",
	N_COM_BLUE:"N_COM_BLUE",
	N_COM_BGDRAW:"N_COM_BGDRAW",
	N_COM_BGCOLOR:"N_COM_BGCOLOR",
	N_COM_X:"N_COM_X",
	N_COM_Y:"N_COM_Y",
	N_COM_W:"N_COM_W",
	N_COM_H:"N_COM_H",
	N_COM_TEXT:"N_COM_TEXT",
	N_COM_TEXTCOLOR:"N_COM_TEXTCOLOR",
	N_COM_FONT:"N_COM_FONT",
	N_COM_FONTSIZE:"N_COM_FONTSIZE",
	N_COM_TEXTGAP:"N_COM_TEXTGAP",
	N_COM_HORALIGN:"N_COM_HORALIGN",
	N_COM_VERALIGN:"N_COM_VERALIGN",
	N_STAT_RED:"N_STAT_RED",
	N_STAT_GREEN:"N_STAT_GREEN",
	N_STAT_BLUE:"N_STAT_BLUE",
	N_STAT_BGDRAW:"N_STAT_BGDRAW",
	N_STAT_BGCOLOR:"N_STAT_BGCOLOR",
	N_STAT_X:"N_STAT_X",
	N_STAT_Y:"N_STAT_Y",
	N_STAT_W:"N_STAT_W",
	N_STAT_H:"N_STAT_H",
	N_STAT_TEXT:"N_STAT_TEXT",
	N_STAT_TEXTCOLOR:"N_STAT_TEXTCOLOR",
	N_STAT_FONT:"N_STAT_FONT",
	N_STAT_FONTSIZE:"N_STAT_FONTSIZE",
	N_STAT_TEXTGAP:"N_STAT_TEXTGAP",
	N_STAT_HORALIGN:"N_STAT_HORALIGN",
	N_STAT_VERALIGN:"N_STAT_VERALIGN",
	N_STRING:"N_STRING",
	N_INT:"N_INT",
	N_ALIGN:"N_ALIGN",
	N_L_SQUIRLY:"N_L_SQUIRLY",
	N_R_SQUIRLY:"N_R_SQUIRLY",
	N_COLOR_DEF:"N_COLOR_DEF",
	N_PAGE_DEF:"N_PAGE_DEF",
	N_BUTTON_DEF:"N_BUTTON_DEF",
	N_PLAINTEXT_DEF:"N_PLAINTEXT_DEF",
	N_TEXTDATA_DEF:"N_TEXTDATA_DEF",
	N_COLOR_BLOCK:"N_COLOR_BLOCK",
	N_PAGE_BLOCK:"N_PAGE_BLOCK",
	N_BUTTON_BLOCK:"N_BUTTON_BLOCK",
	N_PLAINTEXT_BLOCK:"N_PLAINTEXT_BLOCK",
	N_PROGRAM:"N_PROGRAM",
	N_ILLEGAL:"N_ILLEGAL",
}

func (nc NodeCode) String() string {
	name, ok := nodeCodeNames[nc]
	if !ok {
		return "UNKNOWN"
	}
	return name
}
